version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - net
  web:
    build: ./client/my-app
    ports:
      - "3000:3000"
    volumes:
      - ./client/my-app:/user/src/app
    depends_on:
      - server
    networks:
      - net
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    # volumes:
    #   - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

# volumes:
#   index_data:
#     driver: local
#   backups:
#     driver: local

networks:
  net:
    driver: bridge